CONTIKI_PROJECT = udp-client udp-server
# TARGET=simplelink
# BOARD=launchpad/cc1312r1
# MAKE_ROUTING = MAKE_ROUTING_RPL_CLASSIC
# CONTIKI_PROJECT = simple-udp-eco
all: $(CONTIKI_PROJECT)

CONTIKI=../..
include $(CONTIKI)/Makefile.include
