CONTIKI_PROJECT = udp-client udp-server
MAKE_ROUTING = MAKE_ROUTING_RPL_CLASSIC
# CONTIKI_PROJECT = simple-udp-eco
all: $(CONTIKI_PROJECT)

# MODULES += os/services/shell

CONTIKI=../..
include $(CONTIKI)/Makefile.include
